/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "on-surface": "#e5e2e3",
        "on-primary-container": "#006970",
        background: "#131314",
        "on-primary-fixed-variant": "#004f54",
        outline: "#849495",
        "on-secondary-fixed-variant": "#3c4d00",
        primary: "#dbfcff",
        "surface-container-high": "#2a2a2b",
        "on-tertiary": "#313030",
        "tertiary-fixed-dim": "#c8c6c5",
        "surface-container-lowest": "#0e0e0f",
        "on-secondary": "#283500",
        "primary-fixed-dim": "#00dbe9",
        "outline-variant": "#3b494b",
        "on-tertiary-fixed": "#1c1b1b",
        "on-secondary-container": "#556d00",
        "surface-container-low": "#1c1b1c",
        "surface-tint": "#00dbe9",
        "tertiary-fixed": "#e5e2e1",
        "on-tertiary-fixed-variant": "#474646",
        "primary-fixed": "#7df4ff",
        "on-background": "#e5e2e3",
        secondary: "#ffffff",
        "primary-container": "#00f0ff",
        "on-tertiary-container": "#605f5e",
        "error-container": "#93000a",
        "surface-variant": "#353436",
        "surface-container": "#201f20",
        "on-error": "#690005",
        "inverse-surface": "#e5e2e3",
        "secondary-fixed-dim": "#abd600",
        error: "#ffb4ab",
        "inverse-on-surface": "#313031",
        tertiary: "#f9f5f5",
        "on-primary-fixed": "#002022",
        "surface-container-highest": "#353436",
        "secondary-fixed": "#c3f400",
        "secondary-container": "#c3f400",
        "on-error-container": "#ffdad6",
        "on-primary": "#00363a",
        "inverse-primary": "#006970",
        "tertiary-container": "#dcd9d8",
        "surface-dim": "#131314",
        "on-secondary-fixed": "#161e00",
        "surface-bright": "#3a393a",
        surface: "#131314",
        "on-surface-variant": "#b9cacb",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "stack-sm": "12px",
        "container-max": "1440px",
        "margin-desktop": "64px",
        "stack-lg": "48px",
        gutter: "32px",
        unit: "8px",
        "margin-mobile": "20px",
        "stack-md": "24px",
      },
      fontFamily: {
        "headline-lg": ["Montserrat", "sans-serif"],
        "headline-xl": ["Montserrat", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "headline-lg-mobile": ["Montserrat", "sans-serif"],
        "label-sm": ["'JetBrains Mono'", "monospace"],
        "label-tech": ["'JetBrains Mono'", "monospace"],
        "body-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl": ["80px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "900" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "400" }],
        "label-tech": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
      },
      maxWidth: {
        "container-max": "1440px",
      },
      keyframes: {
        scan: {
          "0%": { transform: "translateY(-100%)" },
          "100%": { transform: "translateY(100vh)" },
        },
        scanlineAnim: {
          "0%": { top: "0" },
          "100%": { top: "100%" },
        },
        fadeIn: {
          to: { opacity: "1" },
        },
        typing: {
          from: { width: "0" },
          to: { width: "100%" },
        },
      },
      animation: {
        scan: "scan 4s linear infinite",
        scanlineAnim: "scanlineAnim 3s linear infinite",
        fadeIn: "fadeIn 0.5s forwards",
        typing: "typing 1s steps(30, end)",
      },
    },
  },
  plugins: [],
};
